### ISSUE TITLE
Typo found!

### ISSUE THREAD

**Issue by 2knal** [collective/Collective#1082]
Found a typo on the https://collective.github.io

**Comment by gforcada** [comment]
Hi @2knal thanks for taking the time to report an issue, to move that issue forward it would be great if you can point where is the problem, and even better if you have a solution for it.

A generic "Typo found" without more context than a link is rather unhelpful.

That page you point to is generated from this repository: https://github.com/collective/collective.github.io

Would you mind creating a pull request fixing that typo?

I'm closing the issue here, as the correct place for it is the other repository I pointed you above.

Thanks for spending your time trying to improve Plone!
