### ISSUE TITLE
Questions on the how the Collective works and modeling for other open source communities

### ISSUE THREAD

**Issue by emanlove** [collective/Collective#1158]
To the Collective Maintainers,

I am working on starting a similar "collective-like" organization for the Robot Framework community and had a few questions about the Collective. I appreciate any answers you may share and thank you for your time.

On the welcome page it notes admin rights on new repositories are relinquished. Is this the default due to members not having admin rights? Or did you setup workflows and permissions for this to occur?

How does the mechanics of Github allow for individual repositories to be self managed? With new repos relinquishing admin rights how are repositories managed at the repository level? What conflicts have you experienced with "every repository open to everyone"?

With the six years of experience using GitHub are there any important lessons learned? Are there any process changes you would make? Are there any tools or services advancements from GitHub that you have considered using or using differently?

Ed

**Comment by thet** [comment]
Hi,

> On the welcome page it notes admin rights on new repositories are relinquished. Is this the default due to members not having admin rights? Or did you setup workflows and permissions for this to occur?

We invite new members and add them to the "Members" group. They can create new repositories but generally do not have admin rights on them. I believe they do have admin rights on own repos they create.

> How does the mechanics of Github allow for individual repositories to be self managed?

In the repositories settings you can add collaborators and grant them different permissions up until admin rights.

I think the collective is doing fine! Anything is open source, the license can be chosen freely...
For the plone organisation we require everyone to sign the "Plone contributors agreement" in order to have the Plone Foundation own all rights on the code in this organisation.

Hope that helps!

**Comment by jensens** [comment]
Also, we have site https://collective.github.io/ where the basics are explained to interested upcoming members.

**Comment by jensens** [comment]
> What conflicts have you experienced with "every repository open to everyone"?

In fact, we never had real conflicts. 

One problem are releases on PyPI if the original owner is no longer involved in the project or not reachable at all. We introduced a PyPI user `collective` and the Plone release team has access to this account. But not every PyPI release has this account set as maintainer and its not mandatory to do so (but the more important of them do).

**Comment by emanlove** [comment]
Thanks for those answers @thet and @jensens! This is very helpful.
