### ISSUE TITLE
I love it!

### ISSUE THREAD

**Issue by golden821man** [collective/Collective#1767]
Hi, I love this one.
Please allow me to join this community.
Thanks.

**Comment by gforcada** [comment]
Hi @golden821man 👋🏾 ! Thanks for reaching out to the Plone collective! 😄 There are also a lot of us that also love Plone 😍 what is it that makes you so excited about it?! 😄  

Technically it is not needed to get into the `collective` organization to be able to contribute, you can report issues, and contribute with Pull Requests without being a member of the `collective` organization.

Actually, due to SPAM, we prefer that new contributors, first provide some contributions, and once we acknowledge that they want to contribute and to easy their future contributions, then we make them part of the `collective` organization.

Plone is huge, it goes from a python backend, to a JS (React) based frontend, as well as a server side rendering frontend.

In which areas would you like to contribute? Is there anything that we can help you navigate and get you up to speed? 😄

**Comment by golden821man** [comment]
I think I can contribute to your organization with my developing skills.
My development involves both python and React and I guess I could be a good member.
What do I have to do now?

**Comment by golden821man** [comment]
Your question is likely asking me why do you like pineapple.
I would say cause I love it...
I can't describe myself what the reason is exactly, but as I said I am really interested in Plone.
In addition, I would like to make an open chat with people like you.
I want to learn more things and share ideas with Plone.

**Comment by jensens** [comment]
The question is, what do you work on? Why do you need access? If you do not need access immediately, please come back later if you have a specific need.

**Comment by golden821man** [comment]
What that specific need could be?

**Comment by jensens** [comment]
> What that specific need could be?

Well, if you don't know...? How shall I?

**Comment by golden821man** [comment]
Um, how can I contribute to Plone?
What do I have to do?
Actually, I am really looking forward to get this badge.
And I am sure that there will be something I can do with my skills.

**Comment by jensens** [comment]
Collective is mostly about Plone add-ons. Go to https://github.com/collective/awesome-plone and look for maintained add-ons. Find the add-on's  repository. Look for open issues. Grab one where you think it matches to your skills. Work on it, provide a pull request, get it merged by a maintainer.
