### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by SAD0XER** [collective/Collective#1775]
> :warning: Please consider, you do not need access to Collective to create a pull request or report an issue.
In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Projects I plan to work on:

1. _My personal portfolio website._
2. _1 Blogging website._
3. _1 College Project_

# My motivation

_I am the explorer of knowledge! So, every day I like to learn something new, that time I got an adrenalin rush secondly my situation is my biggest inspiration. As well as really liking to interact with enthusiastic people._

> **Wake with Determination and Sleep with Satisfaction!"**

`PS: Sorry, I have edited this issue template.`

**Comment by gforcada** [comment]
Hi! That is all good and cool, thanks for reaching to us.

Please do consider sending pull requests, filling issues here in GitHub and generaatlly getting in touch with Plone community  community.plone.org 😄 

Getting access to the collective organization is a bit stricter since a feed spam.attacks we got unfortunately

**Comment by SAD0XER** [comment]
Thank You! :smile:
