### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by preciousimo** [collective/Collective#1827]
Please consider, you do not need access to collective to create a pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read [https://collective.github.io/](https://collective.github.io/)
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. **zpretty**
   - [zpretty GitHub Repository](https://github.com/collective/zpretty)

2. **collective.regenv**
   - [collective.regenv GitHub Repository](https://github.com/collective/collective.regenv)

# My motivation

**zpretty:**
I am enthusiastic about improving code quality and readability. The zpretty tool aligns with my interest in maintaining clean and well-formatted HTML, XML, and text containing XML snippets. By contributing to zpretty, I aim to enhance its functionality, address issues, and ensure it remains a valuable resource for developers working with structured document formats.

**collective.regenv:**
I am passionate about configuration management and flexibility within Plone projects. The collective.regenv product provides a means to override values stored in the portal registry and property manager object, offering a high degree of customization. My motivation for contributing to collective.regenv is to extend its capabilities, fix any existing issues, and contribute to making it even more robust for the Plone community. I believe in the importance of empowering Plone developers with effective tools for managing configuration settings.

Thank you!

**Comment by gforcada** [comment]
Hi @preciousimo 👋🏾 ! Thanks for reaching out to the Plone collective! 😄

Technically it is not needed to get into the `collective` organization to be able to contribute, you can report issues, and contribute with Pull Requests without being a member of the `collective` organization.

Actually, due to SPAM, we prefer that new contributors, first provide some contributions, and once we acknowledge that they want to contribute and to easy their future contributions, then we make them part of the `collective` organization.

Please, after doing some contributions, a few PRs, opening a few issues, etc, we will gladly add you to the organization 👍🏾 

We are looking forward to it! 🎉
