### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by solvibrain** [collective/Collective#1843]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. I am Learning Python and also build Project using Django. Now I want to work on Open Source Project and want to learn , how to Collaborate with People on the Same Software Remotely.
2. I am trying to Understand code base of Plone. But I need help from Members to Understand this.

# My motivation
I want to Start My own Company but I have no Background but I know that with Technology I can initiate in the Process with No prior money, just need a lot of hardwork and right Mentorship. I know If I learned the Technology and build the Product which is solving Problem of Peoples , Thus, My dream will come True.
...

Thank you!

**Comment by gforcada** [comment]
Hi @solvibrain  👋🏾 ! Thanks for reaching out to the Plone collective! 😄

Technically it is not needed to get into the `collective` organization to be able to contribute, you can report issues, and contribute with Pull Requests without being a member of the `collective` organization.

Actually, due to SPAM, we prefer that new contributors, first provide some contributions, and once we acknowledge that they want to contribute and to easy their future contributions, then we make them part of the `collective` organization.

Plone is huge, it goes from a python backend, to a JS (React) based frontend, as well as a server side rendering frontend.

In which areas would you like to contribute? Is there anything that we can help you navigate and get you up to speed? 😄
