### ISSUE TITLE
Hope to join

### ISSUE THREAD

**Issue by YSHgroup** [collective/Collective#1874]
I want to contribute and collaborate with this org.
Thank you

**Comment by gforcada** [comment]
Hi @YSHgroup  👋🏾 ! Thanks for reaching out to the Plone collective! 😄

Technically it is not needed to get into the `collective` organization to be able to contribute, you can report issues, and contribute with Pull Requests without being a member of the `collective` organization.

Actually, due to SPAM, we prefer that new contributors, first provide some contributions, and once we acknowledge that they want to contribute and to easy their future contributions, then we make them part of the `collective` organization.

Plone is huge, it goes from a python backend, to a JS (React) based frontend, as well as a server side rendering frontend.

In which areas would you like to contribute? Is there anything that we can help you navigate and get you up to speed? 😄

**Comment by tedster0629** [comment]
Hi @YSHgroup 👋🏾! You don't need to be part of the Plone collective to contribute. Just report issues and submit pull requests. We prefer new contributors to first make some contributions before joining the collective to avoid spam. Plone has a Python backend, a React-based frontend, and a server-side rendering frontend. Let us know which areas you'd like to contribute to, and we can help you get started.
