### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Durgesh4993** [collective/Collective#1876]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. plone.app.multilingual: This project deals with multilingual content management in Plone. You could contribute by adding new language features, improving existing functionalities, or fixing bugs related to multilingual support.

2. Products.CMFPlone: This is the core repository for Plone, where you can contribute to various aspects such as user interface improvements, backend optimizations, accessibility enhancements, or documentation updates.

# My motivation
I'm passionate about open source and believe in its power to drive innovation. Contributing to Plone projects allows me to give back to a platform that's been crucial in content management and web development. I'm eager to improve [plone.app.multilingual] and [Products.CMFPlone], enhance user experiences, and collaborate with the Plone community. This opportunity not only lets me grow technically but also contributes to a community I deeply respect.

...

Thank you!

**Comment by Durgesh4993** [comment]
Intro: I am a full stack PHP & MERN Developer. And also worked as an Open Source Developer. As an Open Source Contributor I have contributed to XWiki, The Tor Project and Omega Up Organization. Currently i am working in Code4govTech Organization under DMP.

**Comment by gforcada** [comment]
Hi @Durgesh4993  👋🏾 ! Thanks for reaching out to the Plone collective! 😄

Technically it is not needed to get into the `collective` organization to be able to contribute, you can report issues, and contribute with Pull Requests without being a member of the `collective` organization.

Actually, due to SPAM, we prefer that new contributors, first provide some contributions, and once we acknowledge that they want to contribute and to easy their future contributions, then we make them part of the `collective` organization.

Plone is huge, it goes from a python backend, to a JS (React) based frontend, as well as a server side rendering frontend.

In which areas would you like to contribute? Is there anything that we can help you navigate and get you up to speed? 😄
